// <auto-generated />
using FractionalAssessment.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FractionalAssessment.Server.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20240819214313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FractionalAssessment.Server.Models.BaseballPlayer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AgeThatYear")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "AgeThatYear");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Handedness")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Bats");

                    b.Property<int>("Hits")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Hits");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "Player");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Year");

                    b.HasKey("ID");

                    b.ToTable("BaseballPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
